a = int(input("enter number 1:"))
b = int(input("enter number 2:"))
c = int(input("enter number 3:"))
d = int(input("enter number 4:"))
e = int(input("enter number 5:"))
f = int(input("enter number 6:"))
g = int(input("enter number 7:"))
h = int(input("enter number 8:"))
i = int(input("enter number 9:"))
j = int(input("enter number 10:"))

m = max(a,b,c,d,e,f,g,h,i,j)
n = min(a,b,c,d,e,f,g,h,h,i,j)

print("Maximum number:",m)
print("Minimum number:",n)